all:
  vars:
    ansible_user: k3s-admin
    ansible_become: true
    rabbitmq_service_ip: 10.20.30.120

kubernetes:
  hosts:
    kubernetes-vip:
      ansible_host: 10.20.30.40

servers:
  hosts:
    k3s-server-cronus:
      ansible_host: 10.20.30.10
      internal_ip: 192.168.100.10
    k3s-server-hyperion:
      ansible_host: 10.20.30.11
      internal_ip: 192.168.100.11
    k3s-server-oceanus:
      ansible_host: 10.20.30.12
      internal_ip: 192.168.100.12

nodes:
  hosts:
    k3s-node-hermes:
      ansible_host: 10.20.30.20
      internal_ip: 192.168.100.20
    k3s-node-achilles:
      ansible_host: 10.20.30.21
      internal_ip: 192.168.100.21
    k3s-node-odysseus:
      ansible_host: 10.20.30.22
      internal_ip: 192.168.100.22
