- name: "Create nginx Kubernetes namespace"
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name: "{{ nginx_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: "Deploy nginx Deployment and Service"
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    namespace: "{{ nginx_namespace }}"
    definition: "{{ lookup('template', item) | from_yaml }}"
  loop:
    - "01-configmap.yml.j2"
    - "02-deployment.yml.j2"
    - "03-service.yml.j2"
