services:
  overpass:
    image: wiktorn/overpass-api
    deploy:
      mode: replicated
      replicas: 3
    environment:
      - OVERPASS_META=yes
      - OVERPASS_MODE=clone
      - OVERPASS_PLANET_URL=http://download.geofabrik.de/europe/italy-latest.osm.bz2-disabled
      - OVERPASS_RATE_LIMIT=0
      - OVERPASS_RATE_SPACE=1073741824
      - OVERPASS_ALLOW_DUPLICATE_QUERIES=yes
    volumes:
      - ./overpass-data:/db
  nginx:
    image: nginx:alpine
    ports:
      - "12345:80"
    volumes:
      - ./nginx:/etc/nginx:ro
    depends_on:
      - overpass

  osrm:
    image: osrm/osrm-backend
    container_name: osrm
    ports:
      - "5000:5000"
    volumes:
      - ./osrm-data:/data
    command: >
      sh -c "
        if [ ! -f /data/italy-latest.osrm ]; then
          osrm-extract -p /opt/car.lua /data/italy-latest.osm.pbf &&
          osrm-partition /data/italy-latest.osrm &&
          osrm-customize /data/italy-latest.osrm;
        fi &&
        osrm-routed --algorithm mld /data/italy-latest.osrm
      "
