---
- name: "Create RabbitMQ Kubernetes namespace"
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name: "{{ rabbitmq_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: "Create RabbitMQ Secrets (Erlang Cookie and admin credentials)"
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    namespace: "{{ rabbitmq_namespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ rabbitmq_app_name }}-secrets"
      stringData:
        rabbitmq_erlang_cookie: "{{ rabbitmq_erlang_cookie }}"
        rabbitmq_admin_user: "{{ rabbitmq_admin_user }}"
        rabbitmq_admin_password: "{{ rabbitmq_admin_password }}"

- name: "Create RabbitMQ TLS certificates Secret"
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    namespace: "{{ rabbitmq_namespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "rabbitmq-certs"
      # Using type Opaque with stringData is straightforward
      type: Opaque
      stringData:
        # These key names must match the paths in rabbitmq.conf
        ca_certificate.pem: "{{ ca_certificate }}"
        server_certificate.pem: "{{ server_certificate }}"
        server_key.pem: "{{ server_key }}"

- name: "Deploy RabbitMQ"
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    namespace: "{{ rabbitmq_namespace }}"
    definition: "{{ lookup('template', item) | from_yaml }}"
  loop:
    - "01-configmap.yml.j2"
    - "02-sa.yml.j2"
    - "03-role.yml.j2"
    - "04-rolebinding.yml.j2"
    - "05-statefulset.yml.j2"
    - "06-headless-service.yml.j2"
    - "07-service.yml.j2"
    - "08-policy-job.yml.j2"
