# rabbitmq.conf
listeners.tcp.default = 5672
management.tcp.port = 15672

ssl_options.cacertfile = /etc/rabbitmq/certs/ca_certificate.pem
ssl_options.certfile   = /etc/rabbitmq/certs/server_certificate.pem
ssl_options.keyfile    = /etc/rabbitmq/certs/server_key.pem
ssl_options.verify     = verify_none
ssl_options.fail_if_no_peer_cert = false
# MQTT Configuration
mqtt.listeners.tcp.default = 1883
mqtt.listeners.ssl.default = 8883
mqtt.allow_anonymous = false
mqtt.vhost = /
mqtt.exchange = amq.topic
policies.mqtt_durable_queues.pattern = ^mqtt\.
policies.mqtt_durable_queues.apply-to = queues
policies.mqtt_durable_queues.definition.durable = true

# Enable custom auth backend
auth_backends.1 = http
auth_http.http_method = post
auth_http.user_path = http://trackeroo-backend:8080/auth/user
auth_http.vhost_path = http://trackeroo-backend:8080/auth/vhost
auth_http.resource_path = http://trackeroo-backend:8080/auth/resource
auth_http.topic_path = http://trackeroo-backend:8080/auth/topic

# Logging
log.console = true
log.console.level = info
