cnpg_operator_url: "https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.27/releases/cnpg-1.27.0.yaml"
tsdb_cluster_manifest: "files/tsdb-cluster.yaml"
cnpg_namespace: "cnpg-system"
tsdb_namespace: "data"
cluster_name: tsdb
instances: 3
image: ghcr.io/skiby7/tsdb:17
storage_size: 8Gi
storage_class: longhorn
database_name: tracker_db
database_user: postgres
admin_user: admin
apps_user: apps
# This should be a secret but rn the cluster is not exposed
admin_password: administrator
apps_password: apps
synchronous_method: any
synchronous_number: 1
data_durability: required
max_connections: 300
