---
grafana_namespace: grafana
grafana_app_name: grafana
grafana_image: grafana/grafana:latest

grafana_admin_user: admin
grafana_admin_password: admin123

grafana_db_type: postgres
# TODOOOOOO
grafana_db_host: tsdb:5432
grafana_db_name: tracker_db
grafana_db_user: admin
grafana_db_password: administrator

grafana_port: 3000

grafana_storage_class: local-path
grafana_storage_size: 1Gi
