brokeroo_namespace: trackeroo
brokeroo_app_name: brokeroo
brokeroo_kafka_broker: kafka.data.svc.cluster.local:9092
brokeroo_image: ghcr.io/skiby7/brokeroo:latest
brokeroo_amqp_queue_name: brokeroo
brokeroo_replicas: 1
brokeroo_port: 8080
