all:
  vars:
    ansible_user: k3s-admin
    ansible_become: true

servers:
  hosts:
    server1:
      ansible_host: 10.20.30.10
      internal_ip: 192.168.100.10
    server2:
      ansible_host: 10.20.30.11
      internal_ip: 192.168.100.11
    server3:
      ansible_host: 10.20.30.12
      internal_ip: 192.168.100.12

nodes:
  hosts:
    node1:
      ansible_host: 10.20.30.20
      internal_ip: 192.168.100.20
    node2:
      ansible_host: 10.20.30.21
      internal_ip: 192.168.100.21
    node3:
      ansible_host: 10.20.30.22
      internal_ip: 192.168.100.22
