---
- name: Ensure namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ namespace }}"
    state: present

- name: Apply PostgreSQL cluster manifest
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'tsdb-cluster.yaml.j2') }}"
