- name: "Create Flink Kubernetes namespace"
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name: "{{ flink_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: "Deploy Flink JobManager and TaskManager"
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    namespace: "{{ flink_namespace }}"
    definition: "{{ lookup('template', item) | from_yaml }}"
  loop:
    - "01-jobmanager.yml.j2"
    - "02-taskmanager.yml.j2"
    - "03-job.yml.j2"
    - "04-jobservice.yml.j2"