kafka_namespace: data
zookeeper_image: confluentinc/cp-zookeeper:7.5.0
kafka_image: confluentinc/cp-kafka:7.5.0

zookeeper_connect: zookeeper.data.svc.cluster.local:2181
zookeeper_tick_time: 2000

kafka_broker_id: 1
kafka_port: 9092
kafka_host_port: 29092