services:
  trackeroo-backend:
    build:
      context: src
      dockerfile: Dockerfile
    healthcheck:
      test: nc -z localhost 8080
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    secrets:
      - users_key
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongo:27017/trackeroo
      - LOG_LEVEL=disabled

  mongo:
    image: mongo:latest
    command: ["mongod", "--bind_ip_all", "--logpath=/dev/null"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  trackeroo-backend-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      trackeroo-backend:
        condition: service_healthy

secrets:
  users_key:
    file: secrets/users_key
