- name: Deploy tsdb
  hosts: kubernetes
  tags:
    - tsdb
    - data
  roles:
    - tsdb

- name: Deploy pgAdmin
  hosts: kubernetes
  tags:
    - pgadmin
    - management
  roles:
    - pgadmin

- name: Deploy Mongo Express
  hosts: kubernetes
  tags:
    - mongo-express
    - management
  roles:
    - mongo-express

- name: Deploy keda
  hosts: kubernetes
  tags:
    - trackeroo
    - keda
  roles:
    - keda

- name: Deploy rabbitmq
  hosts: kubernetes
  tags:
    - rabbitmq
    - trackeroo
  vars_files:
    - secrets.yml
  roles:
    - rabbitmq

- name: Deploy mongo
  hosts: kubernetes
  tags:
    - mongo
    - data
  roles:
    - mongo

- name: Deploy redis
  hosts: kubernetes
  tags:
    - redis
    - data
  roles:
    - redis

- name: Deploy trackeroo-backend
  hosts: kubernetes
  tags:
    - trackeroo
    - trackeroo-backend
  vars_files:
    - secrets.yml
  roles:
    - trackeroo

- name: Deploy Kafka and Zookeeper
  hosts: kubernetes
  tags:
    - kafka
    - data
  roles:
    - kafka

- name: Deploy Flink
  hosts: kubernetes
  tags:
    - flink
    - data
  roles:
    - flink

- name: Deploy Brokeroo
  hosts: kubernetes
  tags:
    - brokeroo
    - trackeroo
  vars_files:
    - secrets.yml
  roles:
    - brokeroo

- name: Deploy Grafana
  hosts: kubernetes
  tags: grafana
  roles:
    - grafana

- name: Deploy Nginx
  hosts: kubernetes
  tags: nginx
  roles:
    - nginx
